name: firebase_crud_example
description: firebase crud example

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^3.24.0
  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0
  uuid: ^2.2.2
  connectivity: ^2.0.2
  flutter_icons: any
  meta: any
  flutter_svg: any
dev_dependencies:
  mockito: any
  pedantic: ^1.9.0
  effective_dart: ^1.0.0 
  firebase_auth_mocks: ^0.5.1
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
      - assets/images/
  fonts:
      - family: Lato
        fonts:
          - asset: assets/fonts/Lato-Regular.ttf
